### ISSUE TITLE
auth is not defined 

### ISSUE THREAD

**Issue by asadullah097** [bitfumes/private-chat-app-with-laravel-vuejs-pusher#15]
I am using laravel 7 with vuejs it give me the error auth is not defined 
![error](https://user-images.githubusercontent.com/38780235/95095482-88400680-0744-11eb-8c0b-7248f93af765.PNG)

**Comment by vipertecpro** [comment]
HOW DID YOU RESOLVED THIS ????????????????????????????????????????

**Comment by asadullah097** [comment]
use the below script in your master blade 
 <script>
 window.auth = {!!auth()->user()!!}
</script>
use these on the view/js/bootsrap.js
window.axios = require('axios');

window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';

let token = document.head.querySelector('meta[name="csrf-token"]');

if (token) {
    window.axios.defaults.headers.common['X-CSRF-TOKEN'] = token.content;
} else {
    console.error('CSRF token not found: https://laravel.com/docs/csrf#csrf-x-csrf-token');
}

**Comment by vipertecpro** [comment]
Yeah Yeah Yeah i got that all by myself , but thax alot for posting this in here, this will defiantly going to help someone else.
